version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: geo-location-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: geo-location-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
